import { StyleSheet } from 'react-native';
import { C } from '@/constants/lootopiaTheme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },

  header: {
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  headerTopLine: { height: 2, backgroundColor: C.gold, opacity: 0.6 },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  headerEyebrow: {
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 4,
    color: C.goldDim,
    textTransform: 'uppercase',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: C.text,
    letterSpacing: 0.5,
    marginTop: -2,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },

  tabRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: C.border,
    marginTop: 4,
  },
  tab: { marginRight: 24, paddingVertical: 12, position: 'relative' },
  tabActive: {},
  tabText: {
    fontSize: 13,
    fontWeight: '500',
    color: C.textMuted,
    letterSpacing: 0.3,
  },
  tabTextActive: { color: C.goldLight },
  tabUnderline: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: C.gold,
    borderRadius: 1,
  },

  countBadge: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  countText: {
    fontSize: 11,
    color: C.textFaint,
    fontFamily: 'monospace',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  listContent: { padding: 16, paddingTop: 12, flexGrow: 1 },

  card: {
    backgroundColor: C.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  cardAccentBar: { width: 3, backgroundColor: C.gold, opacity: 0.7 },
  cardInner: { flex: 1, padding: 14 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardHeaderLeft: { flexDirection: 'row', alignItems: 'center' },
  huntNumberBadge: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: C.border,
  },
  huntNumberText: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: C.goldDim,
    letterSpacing: 1,
  },
  difficultyRow: { flexDirection: 'row', gap: 4 },
  difficultyDot: { width: 7, height: 7, borderRadius: 4 },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: C.text,
    lineHeight: 22,
    letterSpacing: 0.2,
    marginBottom: 8,
  },
  cardDivider: { height: 1, backgroundColor: C.border, marginBottom: 8 },
  cardDesc: {
    fontSize: 13,
    color: C.textMuted,
    lineHeight: 19,
    marginBottom: 12,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardFooterLeft: { flexDirection: 'row', alignItems: 'center' },
  cardMeta: {
    fontSize: 11,
    color: C.textFaint,
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  chevronContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: C.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
  },
  chevron: { fontSize: 16, color: C.gold, lineHeight: 20, marginLeft: 1 },

  pRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 8,
  },
  pBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pBtnOff: { opacity: 0.25 },
  pArrow: { fontSize: 22, color: C.gold, lineHeight: 30, fontWeight: '600' },
  pArrowOff: { color: C.textFaint },
  pNumbers: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  pNum: {
    minWidth: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  pNumActive: { backgroundColor: C.gold, borderColor: C.gold },
  pNumText: { fontSize: 13, color: C.textMuted, fontFamily: 'monospace' },
  pNumTextActive: { color: C.bg, fontWeight: '700' },
  pEllipsis: { fontSize: 13, color: C.textFaint, paddingHorizontal: 2 },

  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
    gap: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: C.textMuted,
    marginTop: 8,
  },
  emptySubtitle: {
    fontSize: 13,
    color: C.textFaint,
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 18,
  },
});